# Dev environment overrides

replicaCount: 1
image:
  tag: "6a678cfdecb24545bde068029dc09fefc3505c4b"
ingress:
  hosts:
    - host: project4-dev.seanxtopher.com
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  enabled: false
