# Prod environment overrides

replicaCount: 2
image:
  tag: "b5832fd5b9bcff7fe1444b314f57ded454443e81"
ingress:
  hosts:
    - host: project4-prod.seanxtopher.com
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
