# Dev environment overrides

replicaCount: 1
image:
  tag: "cfddcc0d4c2a5798f529485c3b1cc575a82a791c"
ingress:
  hosts:
    - host: project4-dev.seanxtopher.com
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  enabled: false
