# Dev environment overrides

replicaCount: 2

image:
  # For now, just a placeholder tag. CI will update this later.
# tag: "dev-latest"
  tag: "v1"

ingress:
  hosts:
    - host: project4-dev.seanxtopher.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

